/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as StructureRouteImport } from './routes/structure'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultIdRouteImport } from './routes/result.$id'
import { Route as AdminStructureRouteImport } from './routes/admin.structure'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StructureRoute = StructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStructureRoute = AdminStructureRouteImport.update({
  id: '/admin/structure',
  path: '/admin/structure',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/structure': typeof StructureRoute
  '/submit': typeof SubmitRoute
  '/users': typeof UsersRoute
  '/admin/structure': typeof AdminStructureRoute
  '/result/$id': typeof ResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/structure': typeof StructureRoute
  '/submit': typeof SubmitRoute
  '/users': typeof UsersRoute
  '/admin/structure': typeof AdminStructureRoute
  '/result/$id': typeof ResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/structure': typeof StructureRoute
  '/submit': typeof SubmitRoute
  '/users': typeof UsersRoute
  '/admin/structure': typeof AdminStructureRoute
  '/result/$id': typeof ResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/structure'
    | '/submit'
    | '/users'
    | '/admin/structure'
    | '/result/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/structure'
    | '/submit'
    | '/users'
    | '/admin/structure'
    | '/result/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/structure'
    | '/submit'
    | '/users'
    | '/admin/structure'
    | '/result/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  StructureRoute: typeof StructureRoute
  SubmitRoute: typeof SubmitRoute
  UsersRoute: typeof UsersRoute
  AdminStructureRoute: typeof AdminStructureRoute
  ResultIdRoute: typeof ResultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure': {
      id: '/structure'
      path: '/structure'
      fullPath: '/structure'
      preLoaderRoute: typeof StructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/structure': {
      id: '/admin/structure'
      path: '/admin/structure'
      fullPath: '/admin/structure'
      preLoaderRoute: typeof AdminStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  StructureRoute: StructureRoute,
  SubmitRoute: SubmitRoute,
  UsersRoute: UsersRoute,
  AdminStructureRoute: AdminStructureRoute,
  ResultIdRoute: ResultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
