/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as StructureRouteImport } from './routes/structure'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppraisalIndexRouteImport } from './routes/appraisal.index'
import { Route as TrainingPlanRouteImport } from './routes/training.plan'
import { Route as TrainingNeedsRouteImport } from './routes/training.needs'
import { Route as TrainingDashboardRouteImport } from './routes/training.dashboard'
import { Route as ResultIdRouteImport } from './routes/result.$id'
import { Route as AppraisalSettingsRouteImport } from './routes/appraisal.settings'
import { Route as AppraisalEmployeesRouteImport } from './routes/appraisal.employees'
import { Route as AdminStructureRouteImport } from './routes/admin.structure'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StructureRoute = StructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppraisalIndexRoute = AppraisalIndexRouteImport.update({
  id: '/appraisal/',
  path: '/appraisal/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingPlanRoute = TrainingPlanRouteImport.update({
  id: '/training/plan',
  path: '/training/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingNeedsRoute = TrainingNeedsRouteImport.update({
  id: '/training/needs',
  path: '/training/needs',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingDashboardRoute = TrainingDashboardRouteImport.update({
  id: '/training/dashboard',
  path: '/training/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppraisalSettingsRoute = AppraisalSettingsRouteImport.update({
  id: '/appraisal/settings',
  path: '/appraisal/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppraisalEmployeesRoute = AppraisalEmployeesRouteImport.update({
  id: '/appraisal/employees',
  path: '/appraisal/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStructureRoute = AdminStructureRouteImport.update({
  id: '/admin/structure',
  path: '/admin/structure',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/structure': typeof StructureRoute
  '/submit': typeof SubmitRoute
  '/users': typeof UsersRoute
  '/admin/structure': typeof AdminStructureRoute
  '/appraisal/employees': typeof AppraisalEmployeesRoute
  '/appraisal/settings': typeof AppraisalSettingsRoute
  '/result/$id': typeof ResultIdRoute
  '/training/dashboard': typeof TrainingDashboardRoute
  '/training/needs': typeof TrainingNeedsRoute
  '/training/plan': typeof TrainingPlanRoute
  '/appraisal/': typeof AppraisalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/structure': typeof StructureRoute
  '/submit': typeof SubmitRoute
  '/users': typeof UsersRoute
  '/admin/structure': typeof AdminStructureRoute
  '/appraisal/employees': typeof AppraisalEmployeesRoute
  '/appraisal/settings': typeof AppraisalSettingsRoute
  '/result/$id': typeof ResultIdRoute
  '/training/dashboard': typeof TrainingDashboardRoute
  '/training/needs': typeof TrainingNeedsRoute
  '/training/plan': typeof TrainingPlanRoute
  '/appraisal': typeof AppraisalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/structure': typeof StructureRoute
  '/submit': typeof SubmitRoute
  '/users': typeof UsersRoute
  '/admin/structure': typeof AdminStructureRoute
  '/appraisal/employees': typeof AppraisalEmployeesRoute
  '/appraisal/settings': typeof AppraisalSettingsRoute
  '/result/$id': typeof ResultIdRoute
  '/training/dashboard': typeof TrainingDashboardRoute
  '/training/needs': typeof TrainingNeedsRoute
  '/training/plan': typeof TrainingPlanRoute
  '/appraisal/': typeof AppraisalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/structure'
    | '/submit'
    | '/users'
    | '/admin/structure'
    | '/appraisal/employees'
    | '/appraisal/settings'
    | '/result/$id'
    | '/training/dashboard'
    | '/training/needs'
    | '/training/plan'
    | '/appraisal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/structure'
    | '/submit'
    | '/users'
    | '/admin/structure'
    | '/appraisal/employees'
    | '/appraisal/settings'
    | '/result/$id'
    | '/training/dashboard'
    | '/training/needs'
    | '/training/plan'
    | '/appraisal'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/structure'
    | '/submit'
    | '/users'
    | '/admin/structure'
    | '/appraisal/employees'
    | '/appraisal/settings'
    | '/result/$id'
    | '/training/dashboard'
    | '/training/needs'
    | '/training/plan'
    | '/appraisal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  StructureRoute: typeof StructureRoute
  SubmitRoute: typeof SubmitRoute
  UsersRoute: typeof UsersRoute
  AdminStructureRoute: typeof AdminStructureRoute
  AppraisalEmployeesRoute: typeof AppraisalEmployeesRoute
  AppraisalSettingsRoute: typeof AppraisalSettingsRoute
  ResultIdRoute: typeof ResultIdRoute
  TrainingDashboardRoute: typeof TrainingDashboardRoute
  TrainingNeedsRoute: typeof TrainingNeedsRoute
  TrainingPlanRoute: typeof TrainingPlanRoute
  AppraisalIndexRoute: typeof AppraisalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure': {
      id: '/structure'
      path: '/structure'
      fullPath: '/structure'
      preLoaderRoute: typeof StructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appraisal/': {
      id: '/appraisal/'
      path: '/appraisal'
      fullPath: '/appraisal/'
      preLoaderRoute: typeof AppraisalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/plan': {
      id: '/training/plan'
      path: '/training/plan'
      fullPath: '/training/plan'
      preLoaderRoute: typeof TrainingPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/needs': {
      id: '/training/needs'
      path: '/training/needs'
      fullPath: '/training/needs'
      preLoaderRoute: typeof TrainingNeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/dashboard': {
      id: '/training/dashboard'
      path: '/training/dashboard'
      fullPath: '/training/dashboard'
      preLoaderRoute: typeof TrainingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appraisal/settings': {
      id: '/appraisal/settings'
      path: '/appraisal/settings'
      fullPath: '/appraisal/settings'
      preLoaderRoute: typeof AppraisalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appraisal/employees': {
      id: '/appraisal/employees'
      path: '/appraisal/employees'
      fullPath: '/appraisal/employees'
      preLoaderRoute: typeof AppraisalEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/structure': {
      id: '/admin/structure'
      path: '/admin/structure'
      fullPath: '/admin/structure'
      preLoaderRoute: typeof AdminStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  StructureRoute: StructureRoute,
  SubmitRoute: SubmitRoute,
  UsersRoute: UsersRoute,
  AdminStructureRoute: AdminStructureRoute,
  AppraisalEmployeesRoute: AppraisalEmployeesRoute,
  AppraisalSettingsRoute: AppraisalSettingsRoute,
  ResultIdRoute: ResultIdRoute,
  TrainingDashboardRoute: TrainingDashboardRoute,
  TrainingNeedsRoute: TrainingNeedsRoute,
  TrainingPlanRoute: TrainingPlanRoute,
  AppraisalIndexRoute: AppraisalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
